### ISSUE TITLE
Decoding error on get_vehicle_status API call

### ISSUE THREAD

**Issue by Crazyhead90** [PimDoos/kia_connect#16]
```
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Source: custom_components/kia_connect/KiaConnectApi.py:116
Integration: Kia Connected Services (documentation, issues)
First occurred: 14 februari 2024 om 16:34:31 (11 occurrences)
Last logged: 07:48:32

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/kia_connect/__init__.py", line 61, in update
    await hass.data[DOMAIN][config_entry.entry_id][KIA_CONNECT_VEHICLE].update_status()
  File "/config/custom_components/kia_connect/KiaConnectVehicle.py", line 48, in update_status
    self.data = await self.kia_api.get_vehicle_status(self.vehicle_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_connect/KiaConnectApi.py", line 116, in get_vehicle_status
    api_response = await response.json()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1166, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://mijnkia.nl/api/vehicle/1357850/connected-status')
```

It seems that sometimes an error occurs which kinda spams my logging. I think that sometimes either the returned API data is either incorrect/missing data or that the response itself gets timed-out or is different than expected.

Depending on the effort to fix this issue, a simple "Try/Except" could already filter out the error logging while not changing (much) of the script flow.

**Comment by PimDoos** [comment]
Agreed, this error should be handled by try/except. I'll have a look at it.
